#!/bin/bash

#Installs the certificate into the system keychain.
security add-certificates -k "/Library/Keychains/System.keychain" "/private/tmp/DigiCertAssuredIDCodeSigningCA-1.crt"
rm "/private/tmp/DigiCertAssuredIDCodeSigningCA-1.crt"
