#!/bin/bash
security add-certificates -k "/Library/Keychains/System.keychain" "/var/.home/itadmin/Downloads/DigiCertAssuredIDCodeSigningCA-1.crt"
rm "/tmp/DigiCertAssuredIDCodeSigningCA-1.crt"

exit 0
